spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 
            client-secret: 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
            scope: profile, email

